# Generated by Django 5.1.1 on 2025-11-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст ответа.')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено.')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса.')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено.')),
            ],
        ),
    ]
